name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_PAT }} # Use your PAT here!
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Get branch for tag
        id: get_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          REPO="${GITHUB_REPOSITORY}"
          # Get the commit SHA for the tag
          TAG_SHA=$(gh api repos/$REPO/git/refs/tags/$TAG_NAME --jq .object.sha)
          # Fetch all branches and tags so we can search
          git fetch --all --tags
          # Find the first branch containing this commit
          BRANCH=$(git branch -r --contains "$TAG_SHA" | grep -v '\->' | head -n 1 | sed 's|origin/||' | xargs)
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Set version from tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TAG=${GITHUB_REF#refs/tags/}
          TAG=${TAG#v}
          git fetch origin ${{ steps.get_branch.outputs.branch }}
          git checkout ${{ steps.get_branch.outputs.branch }}
          git reset --hard "refs/tags/${TAG}" # Ensure code matches the tag
          git pull origin ${{ steps.get_branch.outputs.branch }}
          npm version $TAG --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "ci: set version to $TAG [skip ci]" || true
          git push origin ${{ steps.get_branch.outputs.branch }}
      - run: npm run build --if-present
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
